version: '3.8'

services:
  # 1. BASE DE DATOS MYSQL
  mysql:
    image: mysql:5.7
    container_name: wp-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppassword123
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"  # Opcional: para herramientas externas
    networks:
      - wp-network

  # 2. WORDPRESS CON NGINX INCLUIDO
  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    container_name: wp-app
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword123
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: true  # Para desarrollo
      WORDPRESS_DEBUG_LOG: true
    volumes:
      - wp_data:/var/www/html
      - ./themes:/var/www/html/wp-content/themes  # Tus temas
      - ./plugins:/var/www/html/wp-content/plugins # Tus plugins
      - ./uploads:/var/www/html/wp-content/uploads # Tus archivos
    ports:
      - "2100:80"  # ← PUERTO DE ACCESO
    networks:
      - wp-network

  # 3. phpMyAdmin PARA GESTIONAR BD
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: wp-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 512M
    ports:
      - "2101:80"  # ← PUERTO PARA phpMyAdmin
    networks:
      - wp-network

  # 4. ADMINER (alternativa a phpMyAdmin - más ligero)
  adminer:
    image: adminer
    container_name: wp-adminer
    restart: unless-stopped
    ports:
      - "2102:8080"  # ← PUERTO PARA Adminer
    networks:
      - wp-network

  # 5. MAILHOG PARA CAPTURAR EMAILS (testing)
  mailhog:
    image: mailhog/mailhog
    container_name: wp-mailhog
    restart: unless-stopped
    ports:
      - "2103:8025"  # ← Web UI
      - "2104:1025"  # ← SMTP
    networks:
      - wp-network

  # 6. PORTAINER PARA GESTIONAR DOCKER (opcional)
  portainer:
    image: portainer/portainer-ce:latest
    container_name: wp-portainer
    restart: unless-stopped
    ports:
      - "2105:9000"  # ← Panel de control
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - wp-network

volumes:
  mysql_data:
    driver: local
  wp_data:
    driver: local
  portainer_data:
    driver: local

networks:
  wp-network:
    driver: bridge
