version: '3.8'  # ← Actualizar versión

x-logging: &logging
  driver: 'json-file'
  options:
    max-size: '20m'
    max-file: '5'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_WORDPRESS_DATABASE}
      - MYSQL_USER=${MYSQL_WORDPRESS_USER}
      - MYSQL_PASSWORD=${MYSQL_WORDPRESS_PASSWORD}
      - MYSQL_INNODB_BUFFER_POOL_SIZE=128M  # ← Optimización
    volumes:
      - mysql_data:/var/lib/mysql  # ← Mejor nombre
    logging: *logging
    command: '--default-authentication-plugin=mysql_native_password --max_connections=100'
    healthcheck:  # ← AGREGADO
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      start_period: 30s
    networks:
      - wp_network  # ← Mejor nombre

  wordpress:
    depends_on:
      mysql:
        condition: service_healthy  # ← MEJORADO
    image: wordpress:php8.2-fpm-alpine  # ← ACTUALIZADO
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=mysql:3306
      - WORDPRESS_DB_NAME=${MYSQL_WORDPRESS_DATABASE}
      - WORDPRESS_DB_USER=${MYSQL_WORDPRESS_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_WORDPRESS_PASSWORD}
      - PHP_MEMORY_LIMIT=256M  # ← AGREGADO
    volumes:
      - ./php-conf/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - wordpress_data:/var/www/html  # ← Mejor nombre
      - ./wp-content:/var/www/html/wp-content  # ← Opcional para desarrollo
    logging: *logging
    networks:
      - wp_network

  nginx:
    depends_on:
      - wordpress
    image: nginx:alpine  # ← Versión genérica
    container_name: nginx
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:-80}:80"      # ← Variable de entorno
      - "${HTTPS_PORT:-443}:443"   # ← Variable de entorno
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d:ro  # ← Solo lectura
      - certbot_data:/etc/letsencrypt
      - wordpress_data:/var/www/html
    logging: *logging
    networks:
      - wp_network
    command: >
      sh -c "
      nginx -g 'daemon off;' &
      while sleep 24h; do nginx -s reload; done
      "

  certbot:
    depends_on:
      - nginx
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot_data:/etc/letsencrypt
      - wordpress_data:/var/www/html
    logging: *logging
    entrypoint: >
      sh -c "
      trap exit TERM;
      while :; do
        certbot renew --quiet;
        sleep 12h;
      done
      "

volumes:
  mysql_data:
  wordpress_data:
  certbot_data:

networks:
  wp_network:
    driver: bridge
