version: '3.8'

services:
  db:
    image: mysql:5.7  # ← CAMBIADO A 5.7
    container_name: wordpress-db
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    command: --default-authentication-plugin=mysql_native_password  # ← IMPORTANTE para WordPress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress-app
    restart: unless-stopped
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    ports:
      - "2100:80"

volumes:
  db_data:
    driver: local
  wordpress_data:
    driver: local
