version: '3.8'

services:
  # 1. BASE DE DATOS MYSQL
  mysql-db:
    image: mysql:8.0
    container_name: homelab-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: RootPasswordSeguro123!
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: WordPressPassword123!
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - homelab-network

  # 2. WORDPRESS
  wordpress:
    image: wordpress:latest
    container_name: homelab-wordpress
    restart: unless-stopped
    ports:
      - "2100:80"  # Acceso local: http://192.168.1.246:2100
    environment:
      WORDPRESS_DB_HOST: mysql-db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: WordPressPassword123!
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mysql-db
    networks:
      - homelab-network

  # 3. CLOUDFLARE TUNNEL (PARA ACCESO INTERNET)
  cloudflared-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: homelab-cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token eyJhIjoiNmRjZGNiYWI4YmMxMmIzNzhjZDUxNjA4NWUwYmRjMWUiLCJ0IjoiOGRhNGViOWItOTQwNi00NzU2LWJmYTktOGVmZDExZDA5ZWY5IiwicyI6Ik5HVmxZMll4TlRndFlXTmxPUzAwTVRRNExXRTFPR0l0TUdaa05EUmxNREZtWXpjNCJ9
    networks:
      - homelab-network

volumes:
  mysql_data:
    driver: local
  wordpress_data:
    driver: local

networks:
  homelab-network:
    driver: bridge
