version: '3.8'

# ============================================================================
# WORDPRESS PRODUCTION STACK - HomeLab
# ============================================================================

networks:
  wordpress-network:
    driver: bridge

volumes:
  wordpress_data:
    driver: local
  mysql_data:
    driver: local
  redis_data:
    driver: local

services:
  wordpress:
    image: wordpress:6.5-php8.2-apache
    container_name: homelab-wordpress-2000
    restart: unless-stopped
    
    ports:
      - "2000:80"
    
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: wordpress_homelab
      WORDPRESS_DB_USER: wp_homelab
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD:-ChangeMe123!}  # ← VALOR POR DEFECTO
      WORDPRESS_TABLE_PREFIX: wp_hl_
      WORDPRESS_DEBUG: 0
      
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'http://a8server.unids.com:2000');
        define('WP_SITEURL', 'http://a8server.unids.com:2000');
        define('WP_REDIS_HOST', 'redis');
        define('WP_REDIS_PORT', 6379);
        define('WP_CACHE', true);
    
    volumes:
      - wordpress_data:/var/www/html
    
    networks:
      - wordpress-network
    
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    container_name: homelab-mysql-2000
    restart: unless-stopped
    
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-ChangeMeRoot456!}  # ← VALOR POR DEFECTO
      MYSQL_DATABASE: wordpress_homelab
      MYSQL_USER: wp_homelab
      MYSQL_PASSWORD: ${DB_PASSWORD:-ChangeMe123!}  # ← VALOR POR DEFECTO
    
    volumes:
      - mysql_data:/var/lib/mysql
    
    networks:
      - wordpress-network
    
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD:-ChangeMeRoot456!}"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: homelab-redis-2000
    restart: unless-stopped
    
    command: redis-server --appendonly yes
    
    volumes:
      - redis_data:/data
    
    networks:
      - wordpress-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: homelab-phpmyadmin-2000
    restart: unless-stopped
    
    ports:
      - "2001:80"
    
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${DB_ROOT_PASSWORD:-ChangeMeRoot456!}  # ← VALOR POR DEFECTO
    
    networks:
      - wordpress-network
    
    depends_on:
      - mysql
