version: '3.8'

# ============================================================================
# WORDPRESS PRODUCTION STACK - HomeLab
# ============================================================================
# Puerto: 2000
# Site Name: HomeLab
# Dominio: a8server.unids.com
# ============================================================================

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
    internal: true

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/wordpress
  mysql_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/mysql
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/redis

services:
  # ==========================================================================
  # WORDPRESS - Aplicación Principal
  # ==========================================================================
  wordpress:
    image: wordpress:6.5-php8.2-apache
    container_name: homelab-wordpress-2000
    
    ports:
      - "2000:80"
      - "20000:443"  # Puerto HTTPS opcional
    
    environment:
      # Conexión a Base de Datos
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: wordpress_homelab
      WORDPRESS_DB_USER: wp_homelab
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD:?Database password required}
      
      # Configuración WordPress
      WORDPRESS_TABLE_PREFIX: wp_hl_
      WORDPRESS_DEBUG: 0
      
      # Configuración Extra de WordPress
      WORDPRESS_CONFIG_EXTRA: |
        /* Site URLs - IMPORTANTE para tu dominio */
        define('WP_HOME', 'http://a8server.unids.com:2000');
        define('WP_SITEURL', 'http://a8server.unids.com:2000');
        
        /* Redis Object Cache */
        define('WP_REDIS_HOST', 'redis');
        define('WP_REDIS_PORT', 6379);
        define('WP_REDIS_DATABASE', 0);
        define('WP_REDIS_TIMEOUT', 1);
        define('WP_REDIS_READ_TIMEOUT', 1);
        define('WP_CACHE', true);
        define('WP_CACHE_KEY_SALT', 'homelab');
        
        /* Seguridad */
        define('FORCE_SSL_ADMIN', false);
        define('DISALLOW_FILE_EDIT', true);
        define('DISALLOW_FILE_MODS', false);
        
        /* Rendimiento */
        define('WP_MEMORY_LIMIT', '256M');
        define('WP_MAX_MEMORY_LIMIT', '512M');
        define('WP_POST_REVISIONS', 10);
        define('AUTOSAVE_INTERVAL', 300);
        define('EMPTY_TRASH_DAYS', 30);
        
        /* Debug */
        define('WP_DEBUG_LOG', false);
        define('WP_DEBUG_DISPLAY', false);
        define('SCRIPT_DEBUG', false);
        
        /* Multisite (deshabilitado por defecto) */
        // define('WP_ALLOW_MULTISITE', false);
        // define('MULTISITE', false);
        // define('SUBDOMAIN_INSTALL', false);
        // define('DOMAIN_CURRENT_SITE', 'a8server.unids.com');
        // define('PATH_CURRENT_SITE', '/');
        // define('SITE_ID_CURRENT_SITE', 1);
        // define('BLOG_ID_CURRENT_SITE', 1);
    
    volumes:
      # WordPress Core & Content
      - wordpress_data:/var/www/html
      
      # Configuraciones personalizadas
      - ./config/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro
      - ./config/apache.conf:/etc/apache2/sites-available/000-default.conf:ro
      - ./config/.htaccess:/var/www/html/.htaccess:ro
      
      # Para desarrollo (opcional)
      - ./plugins:/var/www/html/wp-content/plugins
      - ./themes:/var/www/html/wp-content/themes
    
    networks:
      - frontend
      - backend
    
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/wp-admin/install.php"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    restart: unless-stopped
    
    labels:
      # Labels para identificación
      - "com.wordpress.site=homelab"
      - "com.wordpress.port=2000"
      - "com.wordpress.domain=a8server.unids.com"
      - "com.wordpress.version=6.5"

  # ==========================================================================
  # MYSQL 8.0 - Base de Datos
  # ==========================================================================
  mysql:
    image: mysql:8.0
    container_name: homelab-mysql-2000
    
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:?Root password required}
      MYSQL_DATABASE: wordpress_homelab
      MYSQL_USER: wp_homelab
      MYSQL_PASSWORD: ${DB_PASSWORD:?Database password required}
      
      # Optimización de rendimiento
      MYSQL_INNODB_BUFFER_POOL_SIZE: 256M
      MYSQL_MAX_CONNECTIONS: 150
    
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --max_allowed_packet=256M
      --innodb_buffer_pool_size=256M
      --innodb_log_file_size=64M
      --innodb_flush_log_at_trx_commit=2
      --slow_query_log=1
      --slow_query_log_file=/var/log/mysql/slow-query.log
      --long_query_time=2
    
    volumes:
      # Datos persistentes
      - mysql_data:/var/lib/mysql
      
      # Configuración personalizada
      - ./config/mysql.cnf:/etc/mysql/conf.d/custom.cnf:ro
      
      # Scripts de inicialización
      - ./init:/docker-entrypoint-initdb.d:ro
      
      # Logs
      - ./logs/mysql:/var/log/mysql
    
    networks:
      - backend
    
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    restart: unless-stopped
    
    labels:
      - "com.wordpress.site=homelab"
      - "com.wordpress.service=mysql"

  # ==========================================================================
  # REDIS - Caché de Objetos
  # ==========================================================================
  redis:
    image: redis:7-alpine
    container_name: homelab-redis-2000
    
    command: >
      redis-server
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --save 60 1000
      --appendonly yes
      --appendfsync everysec
    
    volumes:
      - redis_data:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf:ro
    
    networks:
      - backend
    
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    
    restart: unless-stopped
    
    labels:
      - "com.wordpress.site=homelab"
      - "com.wordpress.service=redis"

  # ==========================================================================
  # PHPMYADMIN - Gestión de Base de Datos (Opcional)
  # ==========================================================================
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: homelab-phpmyadmin-2000
    
    ports:
      - "2001:80"
    
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${DB_ROOT_PASSWORD}
      UPLOAD_LIMIT: 256M
      MEMORY_LIMIT: 512M
      MAX_EXECUTION_TIME: 300
    
    networks:
      - backend
    
    depends_on:
      - mysql
    
    profiles:
      - tools
    
    restart: unless-stopped

  # ==========================================================================
  # NGINX - Proxy Inverso (Opcional, alternativa a Apache)
  # ==========================================================================
  nginx:
    image: nginx:alpine
    container_name: homelab-nginx-2000
    
    ports:
      - "2080:80"
      - "2443:443"
    
    volumes:
      - wordpress_data:/var/www/html:ro
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx-homelab.conf:/etc/nginx/conf.d/default.conf:ro
      - ./config/ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx
    
    networks:
      - frontend
    
    depends_on:
      - wordpress
    
    profiles:
      - nginx
    
    restart: unless-stopped

  # ==========================================================================
  # WP-CLI - Línea de Comandos de WordPress (Opcional)
  # ==========================================================================
  wpcli:
    image: wordpress:cli-php8.2
    container_name: homelab-cli-2000
    
    user: "33:33"  # www-data user
    
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: wordpress_homelab
      WORDPRESS_DB_USER: wp_homelab
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
    
    volumes:
      - wordpress_data:/var/www/html
    
    networks:
      - backend
    
    depends_on:
      - mysql
    
    profiles:
      - tools
    
    entrypoint: wp
    command: "--info"

  # ==========================================================================
  # BACKUP - Backups Automáticos (Opcional)
  # ==========================================================================
  backup:
    image: fradelg/mysql-cron-backup
    container_name: homelab-backup-2000
    
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASS: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: wordpress_homelab
      
      # Horario de backups (formato cron)
      CRON_TIME: "0 3 * * *"  # Diario a las 3 AM
      
      # Retención
      MAX_BACKUPS: 30
      INIT_BACKUP: 0
      
      # Compresión
      GZIP_LEVEL: 9
    
    volumes:
      - ./backups:/backup
      - wordpress_data:/var/www/html:ro
    
    networks:
      - backend
    
    depends_on:
      - mysql
    
    profiles:
      - backup
    
    restart: unless-stopped

  # ==========================================================================
  # PORTAINER - Gestión de Docker (Opcional)
  # ==========================================================================
  portainer:
    image: portainer/portainer-ce:latest
    container_name: homelab-portainer-2000
    
    ports:
      - "29000:9000"
      - "29443:9443"
    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/portainer:/data
    
    command: -H unix:///var/run/docker.sock
    
    profiles:
      - management
    
    restart: unless-stopped
